"""add submitted_name to prayer_requests

Revision ID: 206b60af6770
Revises: e611e34244fb
Create Date: 2026-05-28 20:05:08.353491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '206b60af6770'
down_revision = 'e611e34244fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('submitted_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_by', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('submitted_name')

    # ### end Alembic commands ###
